mod 'boxen',  '3.10.3', :github_tarball => 'boxen/puppet-boxen'
mod 'qt',     '1.4.2',  :github_tarball => 'boxen/puppet-qt'
#mod 'stdlib', '3.0.0',  :github_tarball => "puppetlabs/puppetlabs-stdlib"
